services:
  mongo:
    restart: always
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
  stocks1-a:
    restart: always
    build: 
      context: ./stocks
    ports:
      - 5001:8000
    env_file:
    - ./stocks/.env
    environment:
      - COLLECTION_NAME=stocks1
    depends_on:
      - mongo
  stocks1-b:
    restart: always
    build: 
      context: ./stocks
    environment:
      - COLLECTION_NAME=stocks1
    env_file:
    - ./stocks/.env
    depends_on:
      - mongo
  stocks2:
    restart: always
    build: 
      context: ./stocks
    ports:
      - 5002:8000
    environment:
      - COLLECTION_NAME=stocks2
    env_file:
      - ./stocks/.env
    depends_on:
      - mongo
  capital-gains:
    restart: always
    build: 
      context: ./capital-gains
    ports:
      - 5003:8080
    env_file:
      - ./capital-gains/.env
    depends_on:
      - mongo
      - stocks1-a
      - stocks2
  nginx:
    restart: always
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - stocks1-a
      - stocks2
      - capital-gains


volumes:
  mongo_data: